// ignore_for_file: avoid_print
import 'dart:io';

String slug(String s) {
  var t = s.toLowerCase().trim().replaceAll(RegExp(r"[''`]"), '');
  t = t.replaceAll(RegExp(r'[^a-z0-9]+'), '-').replaceAll(RegExp(r'^-+|-+$'), '');
  if (t.isEmpty) t = 'word';
  return '$t.png';
}

String dq(String s) {
  var e = s.replaceAll('\\', '\\\\').replaceAll('\$', '\\\$\n'.trim());
  // fix above: escape dollar
  e = s.replaceAll('\\', '\\\\').replaceAll('\$', '\\\x24');
  if (e.contains("'")) {
    e = e.replaceAll('"', '\\"');
    return '"$e"';
  } else {
    e = e.replaceAll("'", "\\'");
    return "'$e'";
  }
}

// Inglizcha -> emoji (429 ta so'z)
const emojis = <String, String>{
  'hello': '👋',
  'goodbye': '👋',
  'please': '🙏',
  'thanks': '🙏',
  'yes': '✅',
  'no': '❌',
  'morning': '🌅',
  'evening': '🌆',
  'night': '🌙',
  'day': '☀️',
  'time': '⏰',
  'today': '📅',
  'tomorrow': '🔜',
  'yesterday': '⏪',
  'friend': '🧑‍🤝‍🧑',
  'family': '👨‍👩‍👧',
  'mother': '👩',
  'father': '👨',
  'brother': '👦',
  'sister': '👧',
  'child': '🧒',
  'man': '👨',
  'woman': '👩',
  'boy': '👦',
  'girl': '👧',
  'people': '🧑‍🤝‍🧑',
  'older brother': '👦',
  'younger brother': '🧒',
  'older sister': '👧',
  'younger sister': '👧',
  'grandfather': '👴',
  'grandmother': '👵',
  'paternal uncle': '👨',
  'maternal uncle': '👨',
  'paternal aunt': '👩',
  'maternal aunt': '👩',
  'son': '👦',
  'daughter': '👧',
  'husband': '🤵',
  'water': '💧',
  'bread': '🍞',
  'meat': '🥩',
  'rice': '🍚',
  'tea': '🍵',
  'milk': '🥛',
  'egg': '🥚',
  'sugar': '🍬',
  'salt': '🧂',
  'eat': '🍽️',
  'drink': '🥤',
  'book': '📖',
  'pen': '🖊️',
  'school': '🏫',
  'teacher': '👩‍🏫',
  'student': '🧑‍🎓',
  'lesson': '📚',
  'word': '🔤',
  'language': '🗣️',
  'question': '❓',
  'answer': '✅',
  'work': '💼',
  'job': '👔',
  'money': '💰',
  'go': '🚶',
  'come': '🏃',
  'see': '👀',
  'look': '👁️',
  'read': '📖',
  'write': '✍️',
  'speak': '🗣️',
  'listen': '🎧',
  'learn': '📚',
  'teach': '👩‍🏫',
  'walk': '🚶',
  'run': '🏃',
  'sleep': '😴',
  'wake up': '⏰',
  'buy': '🛒',
  'sell': '💵',
  'help': '🤝',
  'like': '👍',
  'love': '❤️',
  'want': '🙏',
  'good': '👍',
  'bad': '👎',
  'big': '🐘',
  'small': '🐭',
  'new': '✨',
  'old': '👴',
  'beautiful': '😍',
  'happy': '😊',
  'sad': '😢',
  'fast': '⚡',
  'slow': '🐢',
  'easy': '😌',
  'difficult': '😓',
  'hot': '🔥',
  'cold': '❄️',
  'sun': '☀️',
  'moon': '🌙',
  'star': '⭐',
  'sky': '🌌',
  'rain': '🌧️',
  'snow': '❄️',
  'tree': '🌳',
  'flower': '🌸',
  'river': '🏞️',
  'mountain': '⛰️',
  'car': '🚗',
  'bus': '🚌',
  'train': '🚂',
  'plane': '✈️',
  'road': '🛣️',
  'city': '🏙️',
  'village': '🏡',
  'market': '🛍️',
  'hospital': '🏥',
  'phone': '📱',
  'head': '🗣️',
  'eye': '👁️',
  'hand': '✋',
  'foot': '🦶',
  'heart': '❤️',
  'computer': '💻',
  'laptop': '💻',
  'tablet': '📱',
  'smartphone': '📱',
  'television': '📺',
  'keyboard': '⌨️',
  'computer mouse': '🖱️',
  'monitor': '🖥️',
  'printer': '🖨️',
  'scanner': '🖨️',
  'headphones': '🎧',
  'charger': '🔌',
  'battery': '🔋',
  'camera': '📷',
  'video camera': '🎥',
  'microphone': '🎤',
  'speaker': '🔊',
  'remote control': '🎛️',
  'screen': '🖥️',
  'cable': '🔌',
  'plug': '🔌',
  'wifi': '📶',
  'internet': '🌐',
  'email': '📧',
  'website': '💻',
  'message': '💬',
  'mobile app': '📲',
  'program': '💾',
  'file': '📁',
  'password': '🔑',
  'robot': '🤖',
  'drone': '🛸',
  'smartwatch': '⌚',
  'game console': '🎮',
  'flash drive': '💾',
  'memory card': '💾',
  'bookstore': '📚',
  'shirt': '👕',
  't-shirt': '👕',
  'pants': '👖',
  'jeans': '👖',
  'shorts': '🩳',
  'dress': '👗',
  'skirt': '👗',
  'blouse': '👚',
  'suit': '🤵',
  'jacket': '🧥',
  'coat': '🧥',
  'raincoat': '🧥',
  'sweater': '🧶',
  'hoodie': '🧥',
  'vest': '🦺',
  'uniform': '👮',
  'shoes': '👞',
  'sneakers': '👟',
  'boots': '🥾',
  'sandals': '🩴',
  'socks': '🧦',
  'hat': '🎩',
  'cap': '🧢',
  'scarf': '🧣',
  'gloves': '🧤',
  'belt': '⛓️',
  'tie': '👔',
  'underwear': '🩲',
  'pajamas': '😴',
  'swimsuit': '🩱',
  'pocket': '👖',
  'button': '🔘',
  'zipper': '🤐',
  'glasses': '👓',
  'sunglasses': '🕶️',
  'watch': '⌚',
  'handbag': '👜',
  'backpack': '🎒',
  'umbrella': '☂️',
  'slippers': '🩴',
  'bathrobe': '🧥',
  'cardigan': '🧶',
  'rain boots': '🥾',
  'high heels': '👠',
  'flip-flops': '🩴',
  'beanie': '🧢',
  'beret': '🎩',
  'headscarf': '🧕',
  'earrings': '💎',
  'necklace': '📿',
  'bracelet': '💍',
  'ring': '💍',
  'wallet': '👛',
  'suitcase': '🧳',
  'overalls': '👖',
  'tracksuit': '🏃',
  'tuxedo': '🤵',
  'polo shirt': '👕',
  'tank top': '🎽',
  'leggings': '👖',
  'tights': '🧦',
  'diaper': '👶',
  'collar': '👔',
  'sleeve': '👕',
  'hanger': '🪝',
  'shoelace': '👟',
  'heel': '👠',
  'bow tie': '🎀',
  'suspenders': '👖',
  'mittens': '🧤',
  'nightgown': '🌙',
  'dog': '🐶',
  'cat': '🐱',
  'bird': '🐦',
  'fish': '🐟',
  'horse': '🐴',
  'cow': '🐄',
  'sheep': '🐑',
  'goat': '🐐',
  'chicken': '🐔',
  'rooster': '🐓',
  'duck': '🦆',
  'goose': '🪿',
  'turkey': '🦃',
  'rabbit': '🐰',
  'mouse': '🐭',
  'pig': '🐷',
  'donkey': '🫏',
  'camel': '🐪',
  'bear': '🐻',
  'wolf': '🐺',
  'fox': '🦊',
  'lion': '🦁',
  'tiger': '🐯',
  'elephant': '🐘',
  'monkey': '🐵',
  'deer': '🦌',
  'snake': '🐍',
  'frog': '🐸',
  'crocodile': '🐊',
  'whale': '🐋',
  'butterfly': '🦋',
  'bee': '🐝',
  'spider': '🕷️',
  'puppy': '🐶',
  'kitten': '🐱',
  'parrot': '🦜',
  'pigeon': '🕊️',
  'sparrow': '🐦',
  'eagle': '🦅',
  'owl': '🦉',
  'shark': '🦈',
  'crab': '🦀',
  'turtle': '🐢',
  'squirrel': '🐿️',
  'hedgehog': '🦔',
  'bat': '🦇',
  'ant': '🐜',
  'fly': '🪰',
  'mosquito': '🦟',
  'giraffe': '🦒',
  'zebra': '🦓',
  'kangaroo': '🦘',
  'panda': '🐼',
  'koala': '🐨',
  'hippopotamus': '🦛',
  'rhinoceros': '🦏',
  'leopard': '🐆',
  'cheetah': '🐆',
  'hyena': '🐺',
  'gorilla': '🦍',
  'chimpanzee': '🐵',
  'lizard': '🦎',
  'alligator': '🐊',
  'chameleon': '🦎',
  'octopus': '🐙',
  'squid': '🦑',
  'jellyfish': '🪼',
  'dolphin': '🐬',
  'penguin': '🐧',
  'ostrich': '🐦',
  'peacock': '🦚',
  'swan': '🦢',
  'stork': '🪶',
  'seagull': '🕊️',
  'falcon': '🦅',
  'canary': '🐤',
  'hen': '🐔',
  'hamster': '🐹',
  'guinea pig': '🐹',
  'mole': '🐀',
  'rat': '🐀',
  'mule': '🫏',
  'ox': '🐂',
  'buffalo': '🐃',
  'lamb': '🐑',
  'calf': '🐄',
  'foal': '🐴',
  'chick': '🐤',
  'worm': '🪱',
  'snail': '🐌',
  'ladybug': '🐞',
  'cockroach': '🪳',
  'grasshopper': '🦗',
  'scorpion': '🦂',
  'eel': '🐟',
  'shrimp': '🦐',
  'lobster': '🦞',
  'starfish': '⭐',
  'apple': '🍎',
  'banana': '🍌',
  'orange': '🍊',
  'mandarin': '🍊',
  'lemon': '🍋',
  'grapes': '🍇',
  'watermelon': '🍉',
  'melon': '🍈',
  'strawberry': '🍓',
  'raspberry': '🍇',
  'cherry': '🍒',
  'apricot': '🍑',
  'peach': '🍑',
  'pear': '🍐',
  'plum': '🍇',
  'pomegranate': '🍎',
  'fig': '🍈',
  'quince': '🍐',
  'persimmon': '🍑',
  'kiwi': '🥝',
  'pineapple': '🍍',
  'mango': '🥭',
  'blueberry': '🫐',
  'fruit': '🍎',
  'coconut': '🥥',
  'date': '🍇',
  'blackberry': '🫐',
  'currant': '🍇',
  'walnut': '🌰',
  'almond': '🌰',
  'pistachio': '🥜',
  'potato': '🥔',
  'onion': '🧅',
  'carrot': '🥕',
  'tomato': '🍅',
  'cucumber': '🥒',
  'cabbage': '🥬',
  'cauliflower': '🥬',
  'broccoli': '🥦',
  'eggplant': '🍆',
  'pepper': '🫑',
  'chili': '🌶️',
  'garlic': '🧄',
  'beet': '🍠',
  'radish': '🔴',
  'turnip': '🌱',
  'pumpkin': '🎃',
  'corn': '🌽',
  'beans': '🫘',
  'peas': '🫛',
  'mushroom': '🍄',
  'lettuce': '🥬',
  'spinach': '🥬',
  'dill': '🌿',
  'parsley': '🌿',
  'vegetable': '🥬',
  'zucchini': '🥒',
  'celery': '🥬',
  'ginger': '🫚',
  'green onion': '🧅',
  'sweet potato': '🍠',
  'mint': '🌿',
  'basil': '🌿',
  'coriander': '🌿',
  'home': '🏠',
  'house': '🏠',
  'room': '🚪',
  'door': '🚪',
  'window': '🪟',
  'wall': '🧱',
  'floor': '🪵',
  'ceiling': '🏠',
  'roof': '🏠',
  'balcony': '🌇',
  'yard': '🏡',
  'garden': '🌳',
  'fence': '🚧',
  'key': '🔑',
  'kitchen': '🍳',
  'bedroom': '🛏️',
  'living room': '🛋️',
  'bathroom': '🛁',
  'toilet': '🚽',
  'shower': '🚿',
  'table': '🍽️',
  'chair': '🪑',
  'bed': '🛏️',
  'sofa': '🛋️',
  'wardrobe': '🗄️',
  'shelf': '🗄️',
  'lamp': '💡',
  'mirror': '🪞',
  'curtain': '🧵',
  'carpet': '🧶',
  'pillow': '💤',
  'blanket': '🛌',
  'fridge': '🧊',
  'stove': '🔥',
  'oven': '🍕',
  'sink': '🚰',
  'ball': '⚽',
};

void main() {
  final inFile = File('lib/data/words.dart');
  final lines = inFile.readAsLinesSync();
  final re = RegExp(r"""Word\(english:\s*('[^']*'|"[^"]*")\s*,\s*uzbek:\s*('[^']*'|"[^"]*")\s*,\s*category:\s*('[^']*'|"[^"]*")\s*\)""");
  String unquote(String q) => q.substring(1, q.length - 1);

  final buf = StringBuffer();
  buf.writeln('// ignore_for_file: prefer_const_constructors');
  buf.writeln('// 🖼️ RASMLI TEST RO\'YXATI — barcha so\'zlar (avto-generatsiya)');
  buf.writeln('// Generator: dart tools/gen_picture_words.dart');
  buf.writeln('// Har bir so\'z emoji-rasm bilan ishlaydi.');
  buf.writeln('// Agar assets/picture_quiz/<slug>.png mavjud bo\'lsa — real foto ko\'rsatiladi,');
  buf.writeln('// bo\'lmasa — katta emoji ko\'rsatiladi. Shuning uchun test internet/rasmsiz ham ishlaydi.');
  buf.writeln('');
  buf.writeln('class PictureWord {');
  buf.writeln('  final String english;');
  buf.writeln('  final String uzbek;');
  buf.writeln('  final String imagePath;');
  buf.writeln('  final String emoji;');
  buf.writeln('  final String category;');
  buf.writeln('');
  buf.writeln('  const PictureWord({');
  buf.writeln('    required this.english,');
  buf.writeln('    required this.uzbek,');
  buf.writeln('    required this.imagePath,');
  buf.writeln('    required this.emoji,');
  buf.writeln('    required this.category,');
  buf.writeln('  });');
  buf.writeln('}');
  buf.writeln('');
  int count = 0;
  buf.writeln('/// Barcha so\'zlar rasmli testda — har safar 10 tasi tasodifiy tushadi.');
  buf.writeln('const List<PictureWord> pictureWords = [');

  for (final l in lines) {
    final m = re.firstMatch(l);
    if (m == null) continue;
    final eng = unquote(m.group(1)!);
    final uzb = unquote(m.group(2)!);
    final cat = unquote(m.group(3)!);
    final key = eng.toLowerCase().trim();
    final emoji = emojis[key] ?? '📝';
    final file = slug(eng);
    buf.writeln(
        "  PictureWord(english: ${dq(eng)}, uzbek: ${dq(uzb)}, imagePath: 'assets/picture_quiz/$file', emoji: '$emoji', category: ${dq(cat)}),");
    count++;
  }
  buf.writeln('];');
  File('lib/data/picture_words.dart').writeAsStringSync(buf.toString());
  print('WROTE $count picture words');
}
